<template>
    <div>
      <div>
        <div class="max-w-5xl mx-auto max-sm:px-6 grid gap-8 py-6">
          <div class="text-center">
            siganos en redes sociales:
          </div>
          <div class="max-w-md text-center mx-auto text-stone-400 grid gap-6">
            <social-v3 />
          </div>
          <div class="text-center font-black">
            CONOZCA MÁS EN NUESTRO SITIO
          </div>
        </div>
      </div>
      <div>
        <div class="max-w-5xl mx-auto text-center py-12 text-stone-400">
          Todos los derechos reservado © — VazTraders
        </div>
      </div>
    </div>
  </template>